[server]
headless = true

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2530"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false
